var age = 25; 
alert("I am 15 Year old" ); 
var visits = 1; 
alert("You have visited this site 14 times"); 
var birthYear = 1990; 
document.write("My birth year is " + birthYear + "." + "<br/>"); 
document.write("Date type of my declared variable is number."+ "<br/>" );
var visitorName = "John Doe"; 
var productTitle = "T-shirt";
var quantity = 5;
document.write(visitorName + " ordered " + quantity + " " + productTitle + "(s) on XYZ Clothing store."); 
var message = "This is a custom alert message.";
